name: COMP3104 GitHub Actions Information
run-name: ${{ github.actor }} is testing Github Actions

on:
  push:
  pull_request:

jobs:
  print-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print event information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Triggered by: ${{ github.actor }}"

      - name: Print repo information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch name: ${{ github.ref_name }}"

      - name: Print runner information
        run: |
          echo "Runner: ${{ runner.os }}"
          echo "Workspace: ${{ github.workspace }}"
          echo "Current directory: $(pwd)"

      - name: List workspace contents
        run: |
          ls -la ${{ github.workspace }}

      - name: Print job status
        run: |
          echo "Job's status: ${{ job.status }}"
